page correction

diff --git a/.github/workflows/publish-quarto.yml b/.github/workflows/publish-quarto.yml
--- a/.github/workflows/publish-quarto.yml
+++ b/.github/workflows/publish-quarto.yml
@@ -1,5 +1,3 @@
-
-
 name: Deploy Quarto site with GitHub Pages
 
 on:
@@ -19,17 +17,10 @@ concurrency:
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
-      - name: Setup Quarto
-        uses: quarto-dev/quarto-actions/setup@v2
-
-      - name: Render Quarto site
-        run: |
-          quarto render docs
-          touch docs/_site/.nojekyll
 
       - name: Setup Pages
         uses: actions/configure-pages@v5
@@ -39,6 +30,14 @@ jobs:
         with:
           r-version: 'release'
           use-public-rspm: true
+
+      # debug
+      - name: Check R installation
+        run: |
+          which R || echo "R not found"
+          which Rscript || echo "Rscript not found"
+          R --version
+        shell: bash
 
       - name: Setup Quarto
         uses: quarto-dev/quarto-actions/setup@v2
@@ -68,6 +67,10 @@ jobs:
             "leaflet.extras"
           ))
         shell: Rscript {0}
+      - name: Render Quarto site
+        run: |
+          quarto render docs
+          touch docs/_site/.nojekyll
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
@@ -75,8 +78,8 @@ jobs:
           path: docs/_site
 
   deploy:
-    needs: build
     runs-on: ubuntu-latest
+    needs: build
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
@@ -85,3 +88,4 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
+
